Repository giraugh/tools, pull requests merged in 2023-04, with the labels that each got.

#1 Add documentation and set up CI for release
  .changeset/README.md
  .changeset/config.json
  .changeset/warm-buses-shake.md
  .github/workflows/release.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  package.json
  yarn.lock
Labels: documentation

#4 Utils for attempting ops and catching errors
  .changeset/warm-toes-try.md
  lib/errors/attemptOrCatch.ts
  lib/errors/attemptOrElse.ts
  lib/errors/index.ts
Labels: enhancement

#7 Fix types of mergeObjectValuesBy
  .changeset/honest-parents-fetch.md
  lib/objects/mergeObjectValuesBy.ts
Labels: bug

#9 Generated and Deployed Docs
  .github/workflows/docs.yml
  .gitignore
  docs/.nojekyll
  docs/README.md
  docs/arrays/arrays.md
  docs/arrays/functions/function.chunkArray.md
  docs/arrays/functions/function.dedupArrayBy.md
  docs/arrays/functions/function.groupArrayBy.md
  docs/arrays/functions/function.partitionArray.md
  docs/arrays/functions/function.range.md
  docs/arrays/functions/function.zipArrays.md
  docs/arrays/functions/function.zipArraysLongest.md
  docs/arrays/types/type-alias.Zipped.md
  docs/arrays/types/type-alias.ZippedLongest.md
  docs/errors/errors.md
  docs/errors/functions/function.expectOrThrow.md
  docs/interpolation/functions/function.lerp.md
  docs/interpolation/interpolation.md
  docs/math/functions/function.product.md
  docs/math/functions/function.sum.md
  docs/math/math.md
  docs/math/variables/variable.EARTH_GRAVITY.md
  docs/math/variables/variable.GOLDEN_RATIO.md
  docs/math/variables/variable.JUPITER_GRAVITY.md
  docs/math/variables/variable.TAU.md
  docs/modules.md
  docs/objects/functions/function.getKey.md
  docs/objects/functions/function.mergeObjectValuesBy.md
  docs/objects/objects.md
  docs/promises/functions/function.filterAsync.md
  docs/promises/functions/function.mapAsync.md
  docs/promises/functions/function.resolveObject.md
  docs/promises/promises.md
  docs/strings/functions/function.capitalize.md
  docs/strings/functions/function.editDistance.md
  docs/strings/functions/function.pluralize.md
  docs/strings/functions/function.truncateWithEllipsis.md
  docs/strings/strings.md
  package.json
  yarn.lock
Labels: documentation, enhancement

#10 Fix docs workflow
  .github/workflows/docs.yml
Labels: documentation

#11 Update docs link in README
  README.md
Labels: documentation

#12 Export types from resolveObject
  .changeset/sweet-bats-lie.md
  lib/promises/resolveObject.ts
Labels: documentation, enhancement

#13 Utils for mapping and filtering objects
  .changeset/fuzzy-pets-work.md
  lib/objects/filterObject.ts
  lib/objects/index.ts
  lib/objects/mapKeys.ts
  lib/objects/mapValues.ts
Labels: enhancement

#15 `logAndReturn` util
  .changeset/two-flies-eat.md
  lib/logging/index.ts
  lib/logging/logAndReturn.ts
Labels: enhancement
